language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t emreeryigit/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true emreeryigit/docker-react npm run test 
